language: objective-c
osx_image: xcode9
env:
  - DESTINATION="OS=11.0,name=iPhone X" SCHEME="Ecno" SDK=iphonesimulator11.0
before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild test -project Ecno.xcodeproj -scheme $SCHEME -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO | xcpretty -c
  - xcodebuild test -project Example.xcodeproj -scheme "Example" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO | xcpretty -c
